Routes:
  - url: /
    description: Game intro page. Start new or join random.

  - url: /account
    description: Edit account details.

  - url: /game/create
    description: Creates a new game instance and returns JSON containing the game session ID.

  - url: /game/<id>
    description: Main game UI.

  - url: /game/random
    description: Redirects user to the URL and returns JSON containing the game session ID.

  - url: /script/view/<id>
    description: View a finished script.

  - url: /template/create
    description: Creates a new template object and returns JSON containing the template ID.
    permissions: Must be a logged in.

  - url: "/template/view/<id>"
    description: View the specified template.
    permissions: Must be a logged in and own the specified template.